name: eofficeapp
description: A new Flutter project.
publish_to: "none"
version: 1.0.6+6

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  share_screenshot_widget: ^0.0.5
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  get: ^4.6.1
  flutter_form_builder: ^9.0.0
  dio_smart_retry: ^5.0.0
  shimmer: ^2.0.0
  cached_network_image: ^3.2.0
  line_icons: ^2.0.1
  url_launcher: ^6.1.11
  accordion: ^2.2.3
  package_info_plus: ^4.0.0
  flutter_secure_storage: ^9.0.0
  skeleton_text: ^3.0.0
  form_builder_validators: ^9.0.0
  form_builder_phone_field: ^2.0.1
  form_builder_extra_fields: ^10.0.0
  image_picker: ^0.8.7+5
  modal_bottom_sheet: ^2.0.1
  infinite_scroll_pagination: ^3.2.0
  pull_to_refresh: ^2.0.0
  html_character_entities: ^1.0.0+1
  persistent_bottom_nav_bar: ^5.0.2
  file: ^6.1.4
  webview_flutter: ^4.2.0
  intl: ^0.18.0
  geolocator: ^9.0.2
  camera: ^0.10.5
  flutter_native_splash: ^2.2.19
  dotted_border: ^2.0.0+3
  flutter_html: ^3.0.0-alpha.6
  printing: ^5.11.0
  file_picker: ^5.3.0
  open_file: ^3.3.2
  background_downloader: ^7.0.2
  permission_handler: ^11.0.0
  photo_view: ^0.14.0
  progress_border: ^0.1.0
  path_provider: ^2.0.15
  uni_links: ^0.5.1
  form_builder_file_picker: ^4.0.0
  easy_debounce: ^2.0.3
  image_gallery_saver: ^2.0.3
  flutter_web_frame: ^1.0.0
  geocoding: ^2.1.0
  pinput: ^2.2.31
  internet_connection_checker: ^0.0.1+3
  flutter_webrtc: ^0.9.48+hotfix.1
  screen_capture_event: ^1.1.1
  screen_capture_restrictions: ^1.0.1
  screenshot: ^2.3.0
  media_projection_creator: ^1.0.0
  share_files_and_screenshot_widgets: ^1.0.6

dependency_overrides:
  camera_android: ^0.10.8+1
  win32: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/Inter/static/Inter-Thin.ttf
          weight: 100
        - asset: assets/Inter/static/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/Inter/static/Inter-Light.ttf
          weight: 300
        - asset: assets/Inter/static/Inter-Regular.ttf
          weight: 400
        - asset: assets/Inter/static/Inter-Medium.ttf
          weight: 500
        - asset: assets/Inter/static/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/Inter/static/Inter-Bold.ttf
          weight: 700
        - asset: assets/Inter/static/Inter-Black.ttf
          weight: 900

    - family: Inter Tight
      fonts:
        - asset: assets/Inter_Tight/static/InterTight-Thin.ttf
          weight: 100
        - asset: assets/Inter_Tight/static/InterTight-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/Inter_Tight/static/InterTight-ExtraLight.ttf
          weight: 200
        - asset: assets/Inter_Tight/static/InterTight-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/Inter_Tight/static/InterTight-Light.ttf
          weight: 300
        - asset: assets/Inter_Tight/static/InterTight-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/Inter_Tight/static/InterTight-Regular.ttf
          weight: 400
        - asset: assets/Inter_Tight/static/InterTight-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/Inter_Tight/static/InterTight-Medium.ttf
          weight: 500
        - asset: assets/Inter_Tight/static/InterTight-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/Inter_Tight/static/InterTight-SemiBold.ttf
          weight: 600
        - asset: assets/Inter_Tight/static/InterTight-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/Inter_Tight/static/InterTight-Bold.ttf
          weight: 700
        - asset: assets/Inter_Tight/static/InterTight-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/Inter_Tight/static/InterTight-Black.ttf
          weight: 900
        - asset: assets/Inter_Tight/static/InterTight-BlackItalic.ttf
          weight: 900
          style: italic

flutter_intl:
  enabled: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_new.png"
  web:
    generate: true
    image_path: "assets/logo_new.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

flutter_native_splash:
  fullscreen: true
  color: "#ffffff"
  image: assets/logo_new.png
  color_dark: "#ffffff"
  image_dark: assets/logo_new.png
  android_12:
    image: assets/logo_new.png
    icon_background_color: "#ffffff"
    image_dark: assets/logo_new.png
    icon_background_color_dark: "#ffffff"
  web: false
